name: Artist Directory CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  quality-checks:
    name: Code Quality & Testing
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Run Full Code Quality & Testing Suite
        run: make ci

  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: quality-checks
    timeout-minutes: 30   # increased timeout for debugging
    defaults:
      run:
        working-directory: infrastructure/terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan with Debug Logs
        run: terraform plan -no-color -input=false -lock-timeout=5m -verbose

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform
    if: github.event_name == 'workflow_dispatch'
    timeout-minutes: 15
    defaults:
      run:
        working-directory: infrastructure/terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
