name: FINAL UNDER-REP CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-checks:
    name: Code Quality & Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: /Users/charleybolton/Desktop/Projects/Artist-Directory/infrastructure/terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: /Users/charleybolton/Desktop/Projects/Artist-Directory/infrastructure/terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: /Users/charleybolton/Desktop/Projects/Artist-Directory/infrastructure/terraform

      - name: Run Make CI
        run: make ci
